### ISSUE TITLE
Error in README.md on step 

### ISSUE THREAD

**Issue by OpenDGPS** [bakerwho/dagster-mvp#2]
Instead of

3. Run using CLI:
    `dagster job execute clean_string_job`

it should be

3. Run using CLI in dagster-mvp directory:
    `dagster job execute -f pipeline_1.py -a clean_string_job`

as the original cmd will produce an error saying 'Error: Got unexpected extra argument (clean_string_job)'.

**Comment by bakerwho** [comment]
Thanks for catching, pushed the fix.
