### ISSUE TITLE
Unknown parameter 'job' in RunRequest 

### ISSUE THREAD

**Issue by OpenDGPS** [bakerwho/dagster-mvp#3]
In `pipeline_1.py` line 114 `RunRequest` is called with parameter 'job'. According to the documentation (https://docs.dagster.io/_apidocs/schedules-sensors) there is no such parameter.

Additional RunRequest is not imported in line 2 by `from dagster import In, Out`. 

Both causes an error if I turn on the scheduling.

It will work with:

```from dagster import In, Out, RunRequest```

and 

```python
@dagster.schedule(job=clean_string_job, cron_schedule="0/1 * * * *", execution_timezone="US/Pacific")
def every_minute_string_job_schedule(context):
    scheduled_date = context.scheduled_execution_time.strftime("%Y-%m-%d %H:%M:%S")
    return RunRequest(
        job_name="clean_string_job",
        tags={"date": scheduled_date}
    )
``` 

(btw: Thnx for sharing this example! It helped me to have my first up and running dagster job scheduling.)

**Comment by bakerwho** [comment]
This code was written to run an unstable version of Dagster (`0.6` iirc). The `RunRequest` calling pattern has changed.

The ImportError was an oversight.

Thanks for catching, I've pushed the fixes.

**Comment by bakerwho** [comment]
Pushed the fix
